///////////////////////////////////////////////////////////
//  Client.cs
//  Implementation of the Class Client
//  Generated by Enterprise Architect
//  Created on:      18-Jul-2016 9:13:57 PM
//  Original author: UserAnonymous
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using MySql.Data.MySqlClient;
using System.Data;



public class Client {

	/// <summary>
	/// end Question
	/// </summary>
	private int _id;
	private string _name;
	private string _lastName;
	private string _rfc;
	private string _phone;
	//private string _cellphone;
	//private string _enterprisePhone;
	private string _email;

	public Client(){
        _name = "";
        _lastName = "";
        _rfc = "";
        _phone = "";
        //_cellphone = "";
        //_enterprisePhone = "";
        _email = "";
	}

	/// <summary>
    /// Client
    /// </summary>
    /// <param name="id">Id</param>
	public Client(int rfc){
        Connection c = new Connection();
        MySqlCommand command = new MySqlCommand(
            "SELECT cli_rfc, cli_name, cli_lastName, cli_phone, cli_email FROM clients WHERE cli_id = ?RFC"
            );
        command.Parameters.AddWithValue("?RFC", rfc);

        DataRow firstRow = c.GetFirstRow(command);
        if (firstRow != null)
        {
            _rfc = firstRow["cli_rfc"].ToString();
            _name = firstRow["cli_name"].ToString();
            _lastName = firstRow["cli_lastname"].ToString();
            _phone = firstRow["cli_phone"].ToString();
        }
        else
            throw new ObjectNotFoundException("Client");
	}

    /// <summary>
    /// Client
    /// </summary>
    /// <param name="name">Name</param>
    /// <param name="lastName">Last Name</param>
    /// <param name="rfc">RFC</param>
    /// <param name="phone">Phone</param>
    /// <param name="email">E-mail</param>
	public Client(string name, string lastName, string rfc, string phone, /*string cellPhone, string enterprisePhone,*/ string email){
        _name = name;
        _lastName = lastName;
        _rfc = rfc;
        _phone = phone;
        _email = email;
        //registrar el cliente
	}

	public int Id{
		get{
			return _id;
		}
		set{
			_id = value;
		}
	}

	public string Name{
		get{
			return _name;
		}
		set{
			_name = value;
		}
	}

	public string LastName{
		get{
			return _lastName;
		}
		set{
			_lastName = value;
		}
	}

    /// <summary>
    /// Client's Full Name
    /// </summary>
    public string FullName
    {
        get
        {
            return _name + " " + _lastName;
        }
    }

    /// <summary>
    /// Client's RFC
    /// </summary>
	public string Rfc{
		get{
			return _rfc;
		}
		set{
			_rfc = value;
		}
	}

    /// <summary>
    /// Client's Phone
    /// </summary>
	public string Phone{
		get{
			return _phone;
		}
		set{
			_phone = value;
		}
	}
    /*
	public string Cellphone{
		get{
			return _cellphone;
		}
		set{
			_cellphone = value;
		}
	}

	public string EnterprisePhone{
		get{
			return _enterprisePhone;
		}
		set{
			_enterprisePhone = value;
		}
	}
    */
    /// <summary>
    /// Client's E-mail
    /// </summary>
	public string Email{
		get{
			return _email;
		}
		set{
			_email = value;
		}
	}

}//end Client