///////////////////////////////////////////////////////////
//  Lot.cs
//  Implementation of the Class Lot
//  Generated by Enterprise Architect
//  Created on:      18-Jul-2016 9:14:01 PM
//  Original author: UserAnonymous
///////////////////////////////////////////////////////////

using MySql.Data.MySqlClient;
using System;
using System.Data;

public class Lot
{

    private int _code;
    private int _quantity;
    private Status _status;
    private DateTime _date;
    private Line _Line;
    private Product _Product;

    public Lot()
    {
        _code = 0;
        _date = new DateTime();
        _status = Status.NOTEVALUATE;
        _quantity = 0;
        _Line = new Line();
        _Product = new Product();
    }

    public Lot(int code)
    {
        Connection c = new Connection();
        MySqlCommand command = new MySqlCommand(
            "SELECT lot_code, lot_date, lot_status, lot_quantity, lin_code, prod_code FROM lots WHERE lot_code = ?CODE"
            );
        command.Parameters.AddWithValue("?CODE", code);

        DataRow lotInfo = c.GetFirstRow(command);
        if (lotInfo != null)
        {
            _code = int.Parse(lotInfo["lot_code"].ToString());
            _date = DateTime.Parse(lotInfo["lot_date"].ToString());
            _status = (Status)int.Parse(lotInfo["lot_status"].ToString());
            _quantity = int.Parse(lotInfo["lot_quantity"].ToString());
            _Product = new Product(int.Parse(lotInfo["prod_code"].ToString()));
            _Line = new Line(int.Parse(lotInfo["lin_code"].ToString()));
        }
        else
            throw new ObjectNotFoundException("Lot");
    }

    public Lot(int code, DateTime date, Status status, int quantity, Product product, Line line)
    {
        _code = code;
        _date = date;
        _status = status;
        _quantity = quantity;
        _Line = line;
        _Product = product;
    }

    public int Code
    {
        get
        {
            return _code;
        }
    }

    public int Quantity
    {
        get
        {
            return _quantity;
        }
        set
        {
            _quantity = value;
        }
    }

    public DateTime Date
    {
        get
        {
            return _date;
        }

        set
        {
            _date = value;
        }
    }

    public Line Line
    {
        get
        {
            return _Line;
        }

        set
        {
            _Line = value;
        }
    }

    public Product Product
    {
        get
        {
            return _Product;
        }

        set
        {
            _Product = value;
        }
    }

    public Status Status
    {
        get
        {
            return _status;
        }

        set
        {
            _status = value;
        }
    }

    public override bool Equals(object obj)
    {
        return obj is Lot && (obj as Lot).Code == _code;
    }
}//end Lot