///////////////////////////////////////////////////////////
//  Operator.cs
//  Implementation of the Class Operator
//  Generated by Enterprise Architect
//  Created on:      18-Jul-2016 9:14:02 PM
//  Original author: UserAnonymous
///////////////////////////////////////////////////////////

using MySql.Data.MySqlClient;
using System.Data;


public class Operator {

	private int _id;
	private string _name;
	private string _lastName;
    private string _mothersLastName;

    /// <summary>
    /// 
    /// </summary>
	public Operator(){
        _id = 0;
        _name = "";
        _lastName = "";
        _mothersLastName = "";
	}

   /// <summary>
   /// 
   /// </summary>
   /// <param name="id"></param>
   /// <param name="name"></param>
   /// <param name="lastName"></param>
   /// <param name="mothersLastName"></param>
	public Operator(int id, string name, string lastName, string mothersLastName){
        _id = id;
        _name = name;
        _lastName = lastName;
        _mothersLastName = mothersLastName;
	}

    /// <summary>
    /// 
    /// </summary>
    /// <param name="id"></param>
	public Operator(int id){
        Connection c = new Connection();
        MySqlCommand operatorCommand = new MySqlCommand(
            "SELECT ope_id, ope_nombre, ope_lastname, ope_mothers_lastname FROM operators WHERE ope_id = ?ID"
            );
        operatorCommand.Parameters.AddWithValue("?ID",id);

        DataRow operatorInfo = c.GetFirstRow(operatorCommand);
        if (operatorCommand != null)
        {
            _id = int.Parse(operatorInfo["ope_id"].ToString());
            _name = operatorInfo["ope_name"].ToString();
            _lastName = operatorInfo["ope_lastname"].ToString();
            _mothersLastName = operatorInfo["ope_mothers_lastname"].ToString();
        }
        else
            throw new ObjectNotFoundException("Operator");
	}

    /// <summary>
    /// 
    /// </summary>
	public int Id{
		get{
			return _id;
		}
		set{
			_id = value;
		}
	}

    /// <summary>
    /// 
    /// </summary>
	public string Name{
		get{
			return _name;
		}
		set{
			_name = value;
		}
	}

    /// <summary>
    /// 
    /// </summary>
	public string LastName{
		get{
			return _lastName;
		}
		set{
			_lastName = value;
		}
	}

    public string MothersLastName
    {
        get
        {
            return _mothersLastName;
        }

        set
        {
            _mothersLastName = value;
        }
    }
}//end Operator