///////////////////////////////////////////////////////////
//  Order.cs
//  Implementation of the Class Order
//  Generated by Enterprise Architect
//  Created on:      18-Jul-2016 9:14:03 PM
//  Original author: UserAnonymous
///////////////////////////////////////////////////////////

using System;
using MySql.Data.MySqlClient;
using System.Data;

public class Order {

	private int _number;
	public Client _Client;
	private DateTime _startDate;
	private DateTime _endDate;

    /// <summary>
    /// Creates a empty Order
    /// </summary>
	public Order(){
        _number = 0;
        _Client = new Client();
        _startDate = new DateTime();
        _endDate = new DateTime();
	}

	/// <summary>
    /// Order from number
    /// </summary>
    /// <param name="number">Id</param>
	public Order(int number){
        Connection c = new Connection();
        MySqlCommand command = new MySqlCommand(
            "SELECT ord_number, cli_id, ord_startdate, ord_enddate FROM orders WHERE ord_id = ?NUMBER"
            );
        command.Parameters.AddWithValue("?NUMBER", number);

        DataRow firstRow = c.GetFirstRow(command);
        if (firstRow != null)
        {
            _number = int.Parse(firstRow["ord_number"].ToString());
            _Client = new Client(int.Parse(firstRow["cli_id"].ToString()));
            _startDate = DateTime.Parse(firstRow["ord_startdate"].ToString());
            if (firstRow["ord_enddate"] != DBNull.Value)
                _endDate = DateTime.Parse(firstRow["ord_enddate"].ToString());
        }
        else
            throw new ObjectNotFoundException("Order");
    }

	/// <summary>
    /// 
    /// </summary>
    /// <param name="client"></param>
    /// <param name="startDate"></param>
	public Order(Client client, DateTime startDate){
        _Client = client;
        _startDate = startDate;
        _endDate = new DateTime();
        // registrar orden
	}

    /// <summary>
    /// 
    /// </summary>
	public DateTime StartDate{
		get{
			return _startDate;
		}
		set{
			_startDate = value;
		}
	}

    /// <summary>
    /// 
    /// </summary>
	public int Number{
		get{
			return _number;
		}
		set{
			_number = value;
		}
	}

    /// <summary>
    /// 
    /// </summary>
	public DateTime EndDate{
		get{
			return _endDate;
		}
		set{
			_endDate = value;
		}
	}

}//end Order