///////////////////////////////////////////////////////////
//  Piece.cs
//  Implementation of the Class Piece
//  Generated by Enterprise Architect
//  Created on:      18-Jul-2016 9:14:03 PM
//  Original author: UserAnonymous
///////////////////////////////////////////////////////////

using System.Data;
using MySql.Data.MySqlClient;

public class Piece {

	private int _code;
	private string _name;
    private Size _Size;

    public Piece(){
        _code = 0;
        _name = "";
        Size = Size.REGULAR;
	}

    /// <summary>
    /// 
    /// </summary>
    /// <param name="code"></param>
	public Piece(int code){
        Connection c = new Connection();
        MySqlCommand command = new MySqlCommand(
            "SELECT pie_code, pie_name, pie_size FROM pieces WHERE pie_code = ?CODE"
            );
        command.Parameters.AddWithValue("?CODE", code);

        DataRow pieceInfo = c.GetFirstRow(command);

        if (pieceInfo != null)
        {
            _code = int.Parse(pieceInfo["pie_code"].ToString());
            _name = pieceInfo["pie_name"].ToString();
            _Size = (Size)pieceInfo["pie_size"];
        }
        else
            throw new ObjectNotFoundException("Piece");
	}

	/// <summary>
    /// 
    /// </summary>
    /// <param name="code"></param>
    /// <param name="name"></param>
    /// <param name="size"></param>
	public Piece(int code, string name, Size size){
        _code = code;
        _name = name;
        _Size = size;
	}

	public int Code{
		get{
			return _code;
		}
		set{
			_code = value;
		}
	}

	public string Name{
		get{
			return _name;
		}
		set{
			_name = value;
		}
	}

    public Size Size
    {
        get
        {
            return _Size;
        }

        set
        {
            _Size = value;
        }
    }
}//end Piece