///////////////////////////////////////////////////////////
//  Product.cs
//  Implementation of the Class Product
//  Generated by Enterprise Architect
//  Created on:      18-Jul-2016 9:14:04 PM
//  Original author: UserAnonymous
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using MySql.Data.MySqlClient;
using System.Data;

public class Product {

	private int _code;
	private string _name;
	private string _description;
    private List<Piece> _pieces;
    private List<Question> _questions;

    /// <summary>
    /// Empty product
    /// </summary>
	public Product(){
        _code = 0;
        _name = "";
        _description = "";
        _pieces = new List<Piece>();
        _questions = new List<Question>();
	}

    /// <summary>
    /// Creates a Product from product code
    /// </summary>
    /// <param name="code">Product's code</param>
	public Product(int code){
        Connection c = new Connection();
        MySqlCommand productCommand = new MySqlCommand(
            "SELECT prod_code, prod_name, prod_description FROM products WHERE prod_code = ?CODE"
            );
        productCommand.Parameters.AddWithValue("?CODE", code);

        DataRow firstRow = c.GetFirstRow(productCommand);
        if (firstRow != null)
        {
            _code = int.Parse(firstRow["prod_code"].ToString());
            _name = firstRow["prod_name"].ToString();
            _description = firstRow["prod_description"].ToString();
        }
        else
            throw new ObjectNotFoundException("Product");
        // Product's pieces
        MySqlCommand productPiecesCommand = new MySqlCommand(
            "SELECT pie_code, pie_name, pie_size FROM pieces_product WHERE prod_code = ?CODE"
            );
        productPiecesCommand.Parameters.AddWithValue("?CODE",code);

        DataTable pieces = c.ExecuteQuery(productPiecesCommand);

        _pieces = new List<Piece>();

        foreach (DataRow row in pieces.Rows)
        {
            _pieces.Add(
                new Piece(int.Parse(row["pie_code"].ToString()), row["pie_name"].ToString(), (Size)int.Parse(row["pie_size"].ToString()))
                );
        }

        // Product's list of questions
        MySqlCommand productQuestionsCommand = new MySqlCommand(
            "SELECT que_id, que_number, que_text FROM questions_product WHERE prod_code = ?CODE"
            );
        productQuestionsCommand.Parameters.AddWithValue("?CODE",code);

        DataTable questions = c.ExecuteQuery(productQuestionsCommand);

        Questions = new List<Question>();
        foreach (DataRow row in questions.Rows)
            Questions.Add(
                new Question(
                    int.Parse(row["que_id"].ToString()), 
                    int.Parse(row["que_number"].ToString()), 
                    row["que_text"].ToString()
                    )
                );
    }

    /// <summary>
    /// Create a Product with values
    /// </summary>
    /// <param name="name">Name</param>
    /// <param name="description">Description</param>
    /// <param name="pieces">Pieces</param>
    /// <param name="questions">Questions</param>
	public Product(int code,string name, string description,List<Piece> pieces, List<Question> questions){
        _code = code;
        _name = name;
        _description = description;
        _pieces = pieces;
        Questions = questions;
	}

	public int Code{
		get{
			return _code;
		}
		set{
			_code = value;
		}
	}

	public string Name{
		get{
			return _name;
		}
		set{
			_name = value;
		}
	}

	public string Description{
		get{
			return _description;
		}
		set{
			_description = value;
		}
	}

    public List<Piece> Pieces
    {
        get
        {
            return _pieces;
        }

        set
        {
            _pieces = value;
        }
    }

    public List<Question> Questions
    {
        get
        {
            return _questions;
        }

        set
        {
            _questions = value;
        }
    }

    public override string ToString()
    {
        return _code+":"+_name;
    }
}//end Product