///////////////////////////////////////////////////////////
//  Question.cs
//  Implementation of the Class Question
//  Generated by Enterprise Architect
//  Created on:      18-Jul-2016 9:14:07 PM
//  Original author: UserAnonymous
///////////////////////////////////////////////////////////

using MySql.Data.MySqlClient;
using System.Data;

public class Question
{

    private int _id;
    private int _number;
    private string _text;

    /// <summary>
    /// 
    /// </summary>
    /// <param name="id"></param>
    public Question(int id)
    {
        Connection c = new Connection();
        MySqlCommand command = new MySqlCommand(
            "SELECT que_id, que_number, que_text FROM questions WHERE que_id = ?ID"
            );
        command.Parameters.AddWithValue("?ID", id);

        DataRow questionInfo = c.GetFirstRow(command);
        if (questionInfo != null)
        {
            _id = int.Parse(questionInfo["que_id"].ToString());
            _number = int.Parse(questionInfo["que_number"].ToString());
            _text = questionInfo["que_text"].ToString();
        }
        else
            throw new ObjectNotFoundException("Question");
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="id"></param>
    /// <param name="number"></param>
    /// <param name="text"></param>
    public Question(int id, int number, string text)
    {
        _id = id;
        _number = number;
        _text = text;
    }
    /// <summary>
    /// 
    /// </summary>
	public Question()
    {
        _id = 0;
        _number = 0;
        _text = "";
    }

    /// <summary>
    /// 
    /// </summary>
	public int Id
    {
        get
        {
            return _id;
        }
        set
        {
            _id = value;
        }
    }

    /// <summary>
    /// 
    /// </summary>
    public int Number
    {
        get
        {
            return _number;
        }

        set
        {
            _number = value;
        }
    }

    /// <summary>
    /// 
    /// </summary>
	public string Text
    {
        get
        {
            return _text;
        }
        set
        {
            _text = value;
        }
    }
}//end Question