///////////////////////////////////////////////////////////
//  Size.cs
//  Implementation of the Enumeration Size
//  Generated by Enterprise Architect
//  Created on:      18-Jul-2016 9:14:06 PM
//  Original author: UserAnonymous
///////////////////////////////////////////////////////////

public enum Size{

    NONE = 0,
	TINY = 1,
	SMALL = 2,
	REGULAR = 3,
	BIG = 4,
	EXTRABIG = 5

}//end Size