/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 30-Jul-2016 1:21:25 AM 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `Answers` CASCADE
;

DROP TABLE IF EXISTS `Clients` CASCADE
;

DROP TABLE IF EXISTS `Composition` CASCADE
;

DROP TABLE IF EXISTS `Items` CASCADE
;

DROP TABLE IF EXISTS `Lots` CASCADE
;

DROP TABLE IF EXISTS `OperatingLine` CASCADE
;

DROP TABLE IF EXISTS `Operators` CASCADE
;

DROP TABLE IF EXISTS `OrderLine` CASCADE
;

DROP TABLE IF EXISTS `Orders` CASCADE
;

DROP TABLE IF EXISTS `Pieces` CASCADE
;

DROP TABLE IF EXISTS `ProductionLines` CASCADE
;

DROP TABLE IF EXISTS `ProductQuestions` CASCADE
;

DROP TABLE IF EXISTS `Products` CASCADE
;

DROP TABLE IF EXISTS `Questions` CASCADE
;

/* Create Tables */

CREATE TABLE `Answers`
(
	`anw_id` INT NOT NULL,
	`anw_value` CHAR(1) 	 NULL,
	`itm_serie` INT NOT NULL,
	`que_id` SMALLINT 	 NULL,
	CONSTRAINT `PK_Answers` PRIMARY KEY (`anw_id` ASC)
)

;

CREATE TABLE `Clients`
(
	`cli_id` INT NOT NULL AUTO_INCREMENT,
	`cli_name` VARCHAR(18) NOT NULL,
	`cli_lastName` VARCHAR(15) NOT NULL,
	`cli_rfc` VARCHAR(13) NOT NULL,
	`cli_phone` VARCHAR(10) NOT NULL,
	`cli_email` NVARCHAR(50) 	 NULL,
	CONSTRAINT `PK_Clients` PRIMARY KEY (`cli_id` ASC)
)

;

CREATE TABLE `Composition`
(
	`comp_id` INT NOT NULL AUTO_INCREMENT,
	`pie_code` BIGINT 	 NULL,
	`prod_code` INT NOT NULL,
	CONSTRAINT `PK_Composition` PRIMARY KEY (`comp_id` ASC, `prod_code` ASC)
)

;

CREATE TABLE `Items`
(
	`itm_serie` INT NOT NULL,
	`lot_code` INT NOT NULL,
	`itm_status` CHAR(3) 	 NULL,
	CONSTRAINT `PK_Items` PRIMARY KEY (`itm_serie` ASC)
)

;

CREATE TABLE `Lots`
(
	`lot_code` INT NOT NULL AUTO_INCREMENT,
	`lot_date` DATETIME 	 NULL,
	`lot_quantity` INTEGER NOT NULL,
	`lin_code` INTEGER NOT NULL,
	`prod_code` INT NOT NULL,
	CONSTRAINT `PK_Lots` PRIMARY KEY (`lot_code` ASC)
)

;

CREATE TABLE `OperatingLine`
(
	`opl_code` BIGINT NOT NULL,
	`opl_date` DATETIME NOT NULL,
	`ope_id` SMALLINT NOT NULL,
	`lin_code` INTEGER NOT NULL,
	CONSTRAINT `PK_OperatingLine` PRIMARY KEY (`opl_code` ASC)
)

;

CREATE TABLE `Operators`
(
	`ope_id` SMALLINT NOT NULL,
	`ope_name` VARCHAR(20) NOT NULL,
	`ope_lastname` VARCHAR(20) NOT NULL,
	`ope_mothers_lastname` VARCHAR(20) NOT NULL,
	CONSTRAINT `PK_Operadores` PRIMARY KEY (`ope_id` ASC)
)

;

CREATE TABLE `OrderLine`
(
	`orli_date` DATETIME NOT NULL,
	`ord_number` INT 	 NULL,
	`lin_code` INTEGER 	 NULL
)

;

CREATE TABLE `Orders`
(
	`ord_number` INT NOT NULL AUTO_INCREMENT,
	`cli_id` INT 	 NULL,
	`ord_stardate` DATE NOT NULL,
	`ord_enddate` DATE NOT NULL,
	CONSTRAINT `PK_Orders` PRIMARY KEY (`ord_number` ASC)
)

;

CREATE TABLE `Pieces`
(
	`pie_code` BIGINT NOT NULL,
	`pie_name` VARCHAR(30) NOT NULL,
	`pie_size` SMALLINT NOT NULL,
	CONSTRAINT `PK_Pieces` PRIMARY KEY (`pie_code` ASC)
)

;

CREATE TABLE `ProductionLines`
(
	`lin_code` INTEGER NOT NULL,
	`lin_name` VARCHAR(30) NOT NULL,
	CONSTRAINT `PK_Lineas` PRIMARY KEY (`lin_code` ASC)
)

;

CREATE TABLE `ProductQuestions`
(
	`prod_code` INT NOT NULL,
	`que_id` SMALLINT NOT NULL,
	CONSTRAINT `PK_ProductQuestions` PRIMARY KEY (`prod_code` ASC, `que_id` ASC)
)

;

CREATE TABLE `Products`
(
	`prod_code` INT NOT NULL AUTO_INCREMENT,
	`prod_name` VARCHAR(50) NOT NULL,
	`prod_description` TEXT 	 NULL,
	CONSTRAINT `PK_Products` PRIMARY KEY (`prod_code` ASC)
)

;

CREATE TABLE `Questions`
(
	`que_id` SMALLINT NOT NULL AUTO_INCREMENT,
	`que_number` TINYINT NOT NULL,
	`que_text` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_Questions` PRIMARY KEY (`que_id` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `Lots` 
 ADD INDEX `IXFK_Lots_Inspections` ()
;

ALTER TABLE `OperatingLine` 
 ADD INDEX `IXFK_OperatingLine_Lines` (`lin_code` ASC)
;

ALTER TABLE `OperatingLine` 
 ADD INDEX `IXFK_OperatingLine_Operators` (`ope_id` ASC)
;

ALTER TABLE `OrderLine` 
 ADD INDEX `IXFK_OrderLine_Orders` (`ord_number` ASC)
;

ALTER TABLE `OrderLine` 
 ADD INDEX `IXFK_OrderLine_ProductionLines` (`lin_code` ASC)
;

ALTER TABLE `Orders` 
 ADD CONSTRAINT `CK_enddate` CHECK (ord_enddate>=ord_startdate)
;

ALTER TABLE `Orders` 
 ADD INDEX `IXFK_Orders_Clients` (`cli_id` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `Answers` 
 ADD CONSTRAINT `FK_Answers_Items`
	FOREIGN KEY (`itm_serie`) REFERENCES `Items` (`itm_serie`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Answers` 
 ADD CONSTRAINT `FK_Answers_Questions`
	FOREIGN KEY (`que_id`) REFERENCES `Questions` (`que_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Composition` 
 ADD CONSTRAINT `FK_Composition_Pieces`
	FOREIGN KEY (`pie_code`) REFERENCES `Pieces` (`pie_code`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Composition` 
 ADD CONSTRAINT `FK_Composition_Products`
	FOREIGN KEY (`prod_code`) REFERENCES `Products` (`prod_code`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Items` 
 ADD CONSTRAINT `FK_Items_Lots`
	FOREIGN KEY (`lot_code`) REFERENCES `Lots` (`lot_code`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Lots` 
 ADD CONSTRAINT `FK_Lots_Lines`
	FOREIGN KEY (`lin_code`) REFERENCES `ProductionLines` (`lin_code`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Lots` 
 ADD CONSTRAINT `FK_Lots_Products`
	FOREIGN KEY (`prod_code`) REFERENCES `Products` (`prod_code`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `OperatingLine` 
 ADD CONSTRAINT `FK_OperatingLine_Lines`
	FOREIGN KEY (`lin_code`) REFERENCES `ProductionLines` (`lin_code`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `OperatingLine` 
 ADD CONSTRAINT `FK_OperatingLine_Operators`
	FOREIGN KEY (`ope_id`) REFERENCES `Operators` (`ope_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `OrderLine` 
 ADD CONSTRAINT `FK_OrderLine_Orders`
	FOREIGN KEY (`ord_number`) REFERENCES `Orders` (`ord_number`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `OrderLine` 
 ADD CONSTRAINT `FK_OrderLine_ProductionLines`
	FOREIGN KEY (`lin_code`) REFERENCES `ProductionLines` (`lin_code`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Orders` 
 ADD CONSTRAINT `FK_Orders_Clients`
	FOREIGN KEY (`cli_id`) REFERENCES `Clients` (`cli_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `ProductQuestions` 
 ADD CONSTRAINT `FK_ProductQuestions_Products`
	FOREIGN KEY (`prod_code`) REFERENCES `Products` (`prod_code`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `ProductQuestions` 
 ADD CONSTRAINT `FK_ProductQuestions_Questions`
	FOREIGN KEY (`que_id`) REFERENCES `Questions` (`que_id`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1 
;
